name: Hola Mundo #definimos el nombre de nuestro workflow

on: #[push, pull_request] #aqui especificamos el evento push, pull request. Aqui podemos especificar mas cosas
  push:
    branches:
      - main
  pull_request:
    branches:
    - main

jobs: #le domaos un nombre representativo 
  hola:
    runs-on: ubuntu-latest 

    steps: #son la unidad mas pequeña que nos vam a  permitir realizar diferentes acciones
    - name: Hola Mundo
      run: echo "Hola mundo"
      # vamos a crear otro step
    - name: touch file
      run: touch hola.txt
    
    - name: Set text
      run: echo "Hola Mundo" >> hola.txt

    - name: Read file
      run: cat hola.txt
    

      #vamos a crear otro job
  other:
    runs-on: ubuntu-latest 
    needs: hola #tambien puede ser asu [hola] . lo que hace esto es que primero se ejecute el otro job y despues recien este y no paralelamente como hace rato
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7        
    - name: LS
      run: ls -al 
      #Lista los archivos en un directorio.-a: Muestra también los archivos ocultos (aquellos cuyo nombre empieza con un punto .)



      
